name    'alkivi-postfix'
version '0.0.1'
source 'https://github.com/alkivi-sas/puppet-postfix'
author 'alkivi'
license 'LGPLv3'
summary 'Controls postfix, spf and dkim using opendkim'
description 'Setup postfix server and setup spk and dkim using opendkim'
project_page 'https://github.com/alkivi-sas/puppet-postfix'
dependency 'puppetlabs/stdlib', '>3.x'
dependency 'puppetlabs/concat', '1.0.0'
#dependency 'puppetlabs/apache', '>0.x'
#dependency 'alkivi/alkivi_base', '>0.x'
